# Generated by Django 4.2.7 on 2023-12-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0005_rename_name_profile_firstname_profile_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
